"""Added department_A and volunteer and url

Revision ID: 134d5ced25e1
Revises: 5dae35aa7e7d
Create Date: 2024-02-28 16:20:42.155751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134d5ced25e1'
down_revision = '5dae35aa7e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('volunteer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('volunteer', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('volunteer', sa.String(length=255), nullable=True))

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('volunteer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('volunteer')
        batch_op.drop_column('department_A')

    with op.batch_alter_table('pending_project', schema=None) as batch_op:
        batch_op.drop_column('volunteer')
        batch_op.drop_column('department_A')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('volunteer')
        batch_op.drop_column('department_A')

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('volunteer')
        batch_op.drop_column('department_A')

    # ### end Alembic commands ###
