"""Added DEPARTMENT TABLE AND ADD dpartment_A to user table

Revision ID: 5dae35aa7e7d
Revises: f42d1fbce600
Create Date: 2024-02-28 09:45:03.218777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dae35aa7e7d'
down_revision = 'f42d1fbce600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department_F', sa.String(length=255), nullable=True))
        batch_op.drop_column('program')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_A', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department_A')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('department_F')
        batch_op.drop_column('department_A')

    # ### end Alembic commands ###
