"""mobile and profile

Revision ID: 61fdd7b94e01
Revises: 2c01339b154f
Create Date: 2024-03-06 18:52:06.583872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fdd7b94e01'
down_revision = '2c01339b154f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
